#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-faraday
Version  : 0.9.2
Release  : 7
URL      : https://rubygems.org/downloads/faraday-0.9.2.gem
Source0  : https://rubygems.org/downloads/faraday-0.9.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : lsof
BuildRequires : ruby
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-multipart-post
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
# Faraday
Faraday is an HTTP client lib that provides a common interface over many
adapters (such as Net::HTTP) and embraces the concept of Rack middleware when
processing the request/response cycle.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n faraday-0.9.2
gem spec %{SOURCE0} -l --ruby > rubygem-faraday.gemspec

%build
gem build rubygem-faraday.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
faraday-0.9.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/faraday-0.9.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/em_http.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/em_http_ssl_patch.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/em_synchrony.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/em_synchrony/parallel_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/excon.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/httpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/patron.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/rack.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/autoload.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/middleware.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/authorization.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/basic_authentication.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/instrumentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/retry.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/token_authentication.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response/raise_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/upload_io.rb
/usr/lib64/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/utils.rb
/usr/lib64/ruby/gems/2.3.0/specifications/faraday-0.9.2.gemspec
