#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-faraday
Version  : 0.9.1
Release  : 5
URL      : https://rubygems.org/downloads/faraday-0.9.1.gem
Source0  : https://rubygems.org/downloads/faraday-0.9.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : lsof
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-minitest
BuildRequires : rubygem-multipart-post
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
# Faraday
Faraday is an HTTP client lib that provides a common interface over many
adapters (such as Net::HTTP) and embraces the concept of Rack middleware when
processing the request/response cycle.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n faraday-0.9.1
gem spec %{SOURCE0} -l --ruby > rubygem-faraday.gemspec

%build
gem build rubygem-faraday.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
faraday-0.9.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/faraday-0.9.1
ruby -v -I.:lib:test test*/*_test.rb || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/faraday-0.9.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EmHttpSslPatch/cdesc-EmHttpSslPatch.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EmHttpSslPatch/certificate_store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EmHttpSslPatch/host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EmHttpSslPatch/ssl_handshake_completed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EmHttpSslPatch/ssl_verify_peer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EmHttpSslPatch/verify_peer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/EventMachine/cdesc-EventMachine.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/cdesc-Manager.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/check_finished-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/perform_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Manager/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/configure_compression-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/configure_proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/configure_socket-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/configure_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/configure_timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/connection_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/read_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/request_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/Options/request_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/cdesc-EMHttp.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/error_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/parallel%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/perform_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/perform_single_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/raise_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMHttp/setup_parallel_manager-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/ParallelManager/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/ParallelManager/cdesc-ParallelManager.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/ParallelManager/perform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/ParallelManager/queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/ParallelManager/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/cdesc-EMSynchrony.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/EMSynchrony/setup_parallel_manager-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Excon/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Excon/cdesc-Excon.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Excon/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Excon/read_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/cdesc-HTTPClient.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/client-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/configure_proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/configure_socket-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/configure_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/configure_timeouts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/HTTPClient/ssl_verify_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/Net/cdesc-Net.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/OpenSSL/SSL/cdesc-SSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/OpenSSL/cdesc-OpenSSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/cdesc-NetHttp.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/configure_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/create_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/net_http_connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/perform_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/ssl_cert_store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/ssl_verify_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttp/with_net_http_connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttpPersistent/cdesc-NetHttpPersistent.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttpPersistent/configure_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttpPersistent/perform_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttpPersistent/proxy_uri;/cdesc-proxy_uri;.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/NetHttpPersistent/with_net_http_connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Parallelism/cdesc-Parallelism.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Parallelism/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Parallelism/supports_parallel%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Parallelism/supports_parallel-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Patron/Request/cdesc-Request.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Patron/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Patron/cdesc-Patron.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Patron/create_session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Patron/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Rack/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Rack/cdesc-Rack.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Rack/execute_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Rack/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stub/cdesc-Stub.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stub/headers_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stub/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stub/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stub/params_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stub/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/NotFound/cdesc-NotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/cdesc-Stubs.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/head-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/new_stub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/patch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/post-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/put-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/Stubs/verify_stubbed_calls-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Test/stubs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/cdesc-Typhoeus.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/configure_proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/configure_socket-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/configure_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/configure_timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/parallel%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/perform_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/read_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/request_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/Typhoeus/setup_parallel_manager-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/cdesc-Adapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Adapter/save_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/AutoloadHelper/all_loaded_constants-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/AutoloadHelper/autoload_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/AutoloadHelper/cdesc-AutoloadHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/AutoloadHelper/load_autoloaded_constants-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ClientError/backtrace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ClientError/cdesc-ClientError.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ClientError/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ClientError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ClientError/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/advance_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/cdesc-CompositeReadIO.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/current_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/ensure_open_and_readable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/CompositeReadIO/rewind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/authorization-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/basic_auth-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/build_exclusive_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/build_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/build_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/builder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/cdesc-Connection.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/default_parallel_manager-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/headers%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/in_parallel%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/in_parallel-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/parallel_manager-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/params%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/path_prefix%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/run_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/set_authorization_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/token_auth-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/url_prefix%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/url_prefix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Connection/with_uri_credentials-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ConnectionFailed/cdesc-ConnectionFailed.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ConnectionOptions/cdesc-ConnectionOptions.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ConnectionOptions/new_builder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/Utils/cdesc-Utils.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/cdesc-Env.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/clear_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/custom_members-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/in_member_set%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/member_set-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/needs_body%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/parallel%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/parse_body%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Env/success%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/FlatParamsEncoder/cdesc-FlatParamsEncoder.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/FlatParamsEncoder/decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/FlatParamsEncoder/encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Middleware/cdesc-Middleware.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Middleware/dependency-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Middleware/inherited-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Middleware/load_error-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Middleware/loaded%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Middleware/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MiddlewareRegistry/cdesc-MiddlewareRegistry.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MiddlewareRegistry/fetch_middleware-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MiddlewareRegistry/load_middleware-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MiddlewareRegistry/lookup_middleware-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MiddlewareRegistry/middleware_mutex-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MiddlewareRegistry/register_middleware-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/MissingDependency/cdesc-MissingDependency.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/NestedParamsEncoder/cdesc-NestedParamsEncoder.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/NestedParamsEncoder/decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/NestedParamsEncoder/encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/attribute_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/each_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/each_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/fetch_error_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/has_value%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/inherited-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/memoized-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/memoized_attributes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/options_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/symbolized_key_set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/value%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Options/values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ParsingError/cdesc-ParsingError.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ProxyOptions/cdesc-ProxyOptions.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ProxyOptions/from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/cdesc-Handler.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/klass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/Handler/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/StackLocked/cdesc-StackLocked.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/assert_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/build-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/build_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/build_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/cdesc-RackBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/handlers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/insert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/insert_after-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/insert_before-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/lock%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/locked%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/raise_if_locked-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/swap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/to_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/use-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RackBuilder/use_symbol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Authorization/build_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Authorization/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Authorization/cdesc-Authorization.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Authorization/header-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Authorization/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/BasicAuthentication/cdesc-BasicAuthentication.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/BasicAuthentication/header-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Instrumentation/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Instrumentation/Options/instrumenter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Instrumentation/Options/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Instrumentation/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Instrumentation/cdesc-Instrumentation.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Instrumentation/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Multipart/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Multipart/cdesc-Multipart.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Multipart/create_multipart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Multipart/has_multipart%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Multipart/process_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Multipart/process_request%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/backoff_factor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/exceptions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/interval-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/interval_randomness-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/max-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/Options/retry_if-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/build_exception_matcher-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/cdesc-Retry.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/matcher;/cdesc-matcher;.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/retry_request%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/Retry/sleep_amount-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/TokenAuthentication/cdesc-TokenAuthentication.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/TokenAuthentication/header-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/TokenAuthentication/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/UrlEncoded/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/UrlEncoded/cdesc-UrlEncoded.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/UrlEncoded/match_content_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/UrlEncoded/mime_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/UrlEncoded/process_request%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/UrlEncoded/request_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/cdesc-Request.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/headers%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/params%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/to_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Request/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RequestOptions/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/RequestOptions/cdesc-RequestOptions.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/ResourceNotFound/cdesc-ResourceNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/dump_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/dump_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/log_body%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/on_complete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Logger/pretty_inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Middleware/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Middleware/cdesc-Middleware.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/Middleware/on_complete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/RaiseError/cdesc-RaiseError.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/RaiseError/on_complete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/RaiseError/response_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/apply_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/cdesc-Response.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/finished%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/marshal_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/marshal_load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/on_complete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Response/success%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/SSLError/cdesc-SSLError.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/SSLOptions/cdesc-SSLOptions.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/SSLOptions/disable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/SSLOptions/verify%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/TimeoutError/cdesc-TimeoutError.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/TimeoutError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/cdesc-Headers.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/include%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/member%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/Headers/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/cdesc-ParamsHash.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/convert_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/include%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/member%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/merge_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/to_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/ParamsHash/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/URI-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/build_nested_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/build_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/cdesc-Utils.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/deep_merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/deep_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/default_params_encoder-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/default_params_encoder-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/default_uri_parser%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/default_uri_parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/escape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/normalize_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/normalize_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/parse_nested_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/parse_query-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/sort_query_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/Utils/unescape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/cdesc-Faraday.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/default_adapter%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/default_adapter-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/default_connection-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/default_connection_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/lib_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/method_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/require_lib-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/require_libs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Faraday/root_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/Object/tap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/faraday-0.9.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/.document
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/LICENSE.md
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/.last_run.json
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/.resultset.json
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/.resultset.json.lock
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/application.css
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/application.js
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/colorbox/border.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/colorbox/controls.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/colorbox/loading.gif
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/colorbox/loading_background.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/favicon_green.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/favicon_red.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/favicon_yellow.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/loading.gif
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/magnify.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_dadada_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-icons_222222_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-icons_2e83ff_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-icons_454545_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-icons_888888_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/assets/0.10.0/smoothness/images/ui-icons_cd0a0a_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/coverage/index.html
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/faraday.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/em_http.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/em_http_ssl_patch.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/em_synchrony.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/em_synchrony/parallel_manager.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/excon.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/httpclient.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http_persistent.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/patron.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/rack.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/typhoeus.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/autoload.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/middleware.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/parameters.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/authorization.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/basic_authentication.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/instrumentation.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/retry.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/token_authentication.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response/raise_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/upload_io.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/cached-bundle
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/console
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/generate_certs
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/package
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/proxy-server
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/release
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/s3-put
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/server
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/script/test
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/default_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/em_http_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/em_synchrony_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/excon_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/httpclient_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/integration.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/logger_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/net_http_persistent_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/net_http_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/patron_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/rack_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/test_middleware_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/adapters/typhoeus_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/authentication_middleware_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/composite_read_io_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/connection_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/env_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/live_server.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/middleware/instrumentation_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/middleware/retry_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/middleware_stack_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/multibyte.txt
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/options_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/parameters_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/request_middleware_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/response_middleware_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/strawberry.rb
/usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.1/test/utils_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/faraday-0.9.1.gemspec
